#For all profiles

server:
 port: 9040
spring:
 application:
  name: service-client
 kafka:
  bootstrap-servers: 127.0.0.1:9092


#dev
---
spring:
 profiles: dev
 datasource:
  url: jdbc:mysql://localhost:3306/dbproject1
  username: root
  password: admin

eureka:
 instance:
  prefer-ip-address: true
 client:
  service-url:
   defaultZone: http://localhost:9020/eureka

#docker
---
spring:
 profiles: docker
 datasource:
  url: jdbc:mysql://host.docker.internal:3306/dbproject1
  username: root
  password: admin 